#################
## PRODUCTION ##
#################
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 235494786522.dkr.ecr.ap-southeast-1.amazonaws.com/peerprep/frontend-app
    container_name: frontend-app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - backend_shared-network
    command: npm run dev

networks:
  backend_shared-network:
    external: true
