#################
## DEVELOPMENT ##
#################
services:
  gateway-service:
    build:
      context: ./gateway-service
      target: development
    container_name: gateway-service
    command: npm run start:dev
    env_file:
      - ./gateway-service/.env
    ports:
      - "4000:4000"
    volumes:
      - ./gateway-service:/app
      - /app/node_modules
    depends_on:
      - questions-service
      - users-service
      - auth-service
    networks:
      - backend-network

  questions-service:
    build:
      context: ./questions-service
      target: development
    container_name: questions-service
    volumes:
      - ./questions-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./questions-service/.env
    networks:
      - backend-network
    ports:
      - "3002:4000"

  users-service:
    build:
      context: ./users-service
      target: development
    container_name: users-service
    command: npm run start:dev
    volumes:
      - ./users-service:/app
      - /app/node_modules
    env_file:
      - ./users-service/.env
    networks:
      - backend-network
    ports:
      - "3001:4000"

  auth-service:
    build:
      context: ./auth-service
      target: development
    container_name: auth-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./auth-service/.env
    networks:
      - backend-network
    ports:
      - "3003:4000"

networks:
  backend-network:
    driver: bridge
