################
## PRODUCTION ##
################
version: "3"
services:
  gateway-service:
    build:
      context: ./gateway-service
      target: production
    container_name: gateway-service
    command: npm run start:prod
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - question-service
      - user-service
      - auth-service
    networks:
      - backend-network

  question-service:
    build:
      context: ./question-service
      target: production
    container_name: question-service
    command: npm run start:prod
    restart: always
    env_file:
      - ./question-service/.env
    networks:
      - backend-network

  user-service:
    build:
      context: ./user-service
      target: production
    container_name: user-service
    command: npm run start:prod
    restart: always
    env_file:
      - ./user-service/.env
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
