apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: peerprep
spec:
  type: ClusterIP
  ports:
    - port: 3004
      targetPort: 3004
      protocol: TCP
  selector:
    app: matching-service
