apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: peerprep
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: user-service
