apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: peerprep
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: gateway-service
