apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: peerprep
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30001
  selector:
    app: gateway-service
