apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: peerprep
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: auth-service
