apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: peerprep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: evanyan13/peerprep-frontend:dev
          ports:
            - containerPort: 3000
          env:
            - name: GATEWAY_URL
              value: "http://gateway-service:4000"
