apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: peerprep
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000 # Custom node port for external access
  selector:
    app: frontend-service
