name: Backend Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Build and Run Docker Compose
        run: docker-compose up -d --build

      - name: Test Backend Health
        run: |
          sleep 10  # Allow time for services to start
          curl -f http://localhost:4000/api || exit 1  # Replace with actual backend health check endpoint

      - name: Stop and Remove Containers
        run: docker-compose down
