apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
  namespace: peerprep
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
  selector:
    app: collaboration-service
