apiVersion: apps/v1
kind: Deployment
metadata:
  name: y-websocket-service
  namespace: peerprep
  labels:
    app: y-websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: y-websocket-service
  template:
    metadata:
      labels:
        app: y-websocket-service
    spec:
      containers:
        - name: y-websocket-service
          image: evanyan13/peerprep-y-websocket-service:latest
          ports:
            - containerPort: 4001
          envFrom:
            - secretRef:
                name: peerprep-secrets
            - configMapRef:
                name: ywebsocket-configmap
      restartPolicy: Always
