apiVersion: v1
kind: Secret
metadata:
  name: peerprep-secrets
  namespace: peerprep
type: Opaque
data:
  MONGO_CONNECTION_STRING: <BASE64_MONGO_CONNECTION_STRING>
  JWT_SECRET: <BASE64_JWT_SECRET>
  JWT_REFRESH_SECRET: <BASE64_JWT_REFRESH_SECRET>
  GOOGLE_CLIENT_ID: <BASE64_GOOGLE_CLIENT_ID>
  GOOGLE_CLIENT_SECRET: <BASE64_GOOGLE_CLIENT_SECRET>
  GITHUB_CLIENT_ID: <BASE64_GITHUB_CLIENT_ID>
  GITHUB_CLIENT_SECRET: <BASE64_GITHUB_CLIENT_SECRET>
  NODEMAILER_GMAIL_PASSWORD: <BASE64_NODEMAILER_GMAIL_PASSWORD>
  OPENAI_API_KEY: <BASE64_OPENAI_API_KEY>
