apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: peerprep
  labels:
    app: question-service
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: question-service
