name: CI Workflow

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      
      # Build Check
      - name: Build Project
        run: npm run build

      # Lint Check
      - name: Lint Code
        run: npm run lint
